#!/bin/bash
### BEGIN INIT INFO
# Provides:          users
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mazi-users
# Description:       mazi-users
### END INIT INFO
wifi_int=$(bash /root/back-end/mazi-current.sh -i wifi | awk {'print $2'})

case "$1" in
  start)
		hostapd_cli -a '/root/back-end/mazi-users.sh' -i $wifi_int &
        ;;
  stop)
        id=$(ps aux | grep -v grep | grep hostapd_cli | awk '{print $2}')
		for pid in $id;do kill $pid >/dev/null 2>&1; done
		;;
  restart)
        id=$(ps aux | grep -v grep | grep hostapd_cli | awk '{print $2}')
		for pid in $id;do kill $pid >/dev/null 2>&1; done
		hostapd_cli -a '/root/back-end/mazi-users.sh' -i $wifi_int &
		;;
        *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
