#!/bin/sh
#set -x
### BEGIN INIT INFO
# Provides:          nodogsplash
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts nodogsplash Server
# Description:       nodogsplash
### END INIT INFO
dog_path="/etc/nodogsplash/nodogsplash.conf"
domain=$(bash /root/back-end/mazi-current.sh -d | awk {'print $NF'})
mode=$(bash /root/back-end/mazi-current.sh -m | awk {'print $NF'}|tr -d '"')
list=$(tr -s 2>/dev/null '\n' ',' < /etc/mazi/users.dat | sed 's/.$//')
case "$1" in
  start)
        sed -f /etc/hostapd/replace.sed /etc/nodogsplash/${mode}.txt > ${dog_path}
        sed -i "s/domain/$domain/g" ${dog_path}
        sed -i "/TrustedMACList/c\TrustedMACList $list" ${dog_path}
        cd /root/      
        nodogsplash/nodogsplash 2>/dev/null
        ;;
  stop)
        ndsctl stop
        ;;
  restart)
        ;;
        *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
#set +x
