#!/bin/bash
### BEGIN INIT INFO
# Provides:          nodogsplash
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts nodogsplash Server
# Description:       nodogsplash
### END INIT INFO
dog_path="/etc/nodogsplash/nodogsplash.conf"
domain=$(bash /root/back-end/mazi-current.sh -d | awk {'print $NF'})
mode=$(bash /root/back-end/mazi-current.sh -m | awk {'print $NF'}|tr -d '"')
list="$(cat /etc/mazi/users.dat 2>/dev/null | awk {'print $1'} | tr -s '\n' ',' | sed 's/.$//')"
case "$1" in
  start)
        sudo sed -f /etc/hostapd/replace.sed /etc/nodogsplash/${mode}.txt > ${dog_path}
        sudo sed -i "s/domain/$domain/g" ${dog_path}
        [ ! -z "$list" ] && sudo sed -i "/TrustedMACList/c\TrustedMACList $list" ${dog_path}
        cd /root/      
        bash back-end/timeout.sh &>/dev/null & 
        sudo nodogsplash/nodogsplash &>/dev/null 
        ;;
  stop)
 	id=$(ps aux | grep back-end/timeout.sh | grep -v 'grep' |awk '{print $2}')
        if [ -z "$id" ] ;then
           sudo  kill $id
        fi	
        sudo ndsctl stop &>/dev/null
        ;;
  restart)
        ;;
        *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
